steps:
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['docker-compose', '-f', './docker-compose.yaml', '-f', './tests/docker-compose.test.yaml', 'run', 'tests']
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['docker-compose', 'up']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  args:
  - '/workspace/clouddeploy'
