version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8000:8000
    # Let the init system handle signals for us.
    # among other things this helps shutdown be fast
    init: true
