name: Run test

on: pull_request

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: false
          target: "test"
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
